#!/bin/bash

URL='https://duckduckgo.com/?q='
QUERY=$(echo 'DuckduckGo' | dmenu -p "Search:")
if [ -n "$QUERY" ]; then
  xdg-open "${URL}${QUERY}" 2> /dev/null
  exec i3-msg [class="^Firefox$"] focus
fi
